use_frameworks!

platform :ios, '10.0'

target 'Syte_Example' do
  pod 'Syte', :path => '../'
  pod 'SVProgressHUD'
  pod 'Toast-Swift'
  pod 'IQKeyboardManagerSwift'

  target 'Syte_Tests' do
    inherit! :search_paths

    
  end
end
